//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRooms.API.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeetingRooms.API.Resources.APIMessage", typeof(APIMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Token está expirado.
        /// </summary>
        internal static string Authorization_Token_Expired {
            get {
                return ResourceManager.GetString("Authorization.Token.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Token é inválido.
        /// </summary>
        internal static string Authorization_Token_Invalid {
            get {
                return ResourceManager.GetString("Authorization.Token.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Token não foi informado.
        /// </summary>
        internal static string Authorization_Token_Missing {
            get {
                return ResourceManager.GetString("Authorization.Token.Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro interno, tente novamente mais tarde.
        /// </summary>
        internal static string Error_GenericError {
            get {
                return ResourceManager.GetString("Error.GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A propriedade Email está fora do padrão correto.
        /// </summary>
        internal static string Property_Email_Format {
            get {
                return ResourceManager.GetString("Property.Email.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A propriedade {0} é obrigatória.
        /// </summary>
        internal static string Property_Empty {
            get {
                return ResourceManager.GetString("Property.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor da propriedade {0} deve ser maior que {1}.
        /// </summary>
        internal static string Property_GreaterThan {
            get {
                return ResourceManager.GetString("Property.GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato da propriedade {0} é inválido.
        /// </summary>
        internal static string Property_Invalid_Format {
            get {
                return ResourceManager.GetString("Property.Invalid.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A propriedade {0} deve tamanho exato de {1} caractere(s).
        /// </summary>
        internal static string Property_Length {
            get {
                return ResourceManager.GetString("Property.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A propriedade {0} deve ter pelo menos {1} caractere(s).
        /// </summary>
        internal static string Property_MinimumLength {
            get {
                return ResourceManager.GetString("Property.MinimumLength", resourceCulture);
            }
        }
    }
}
